### PR TITLE
Fixed bug that frame action may be miss

### PR DESCRIPTION
**Pull request by k8w**
Relative to https://github.com/jiborobot/pixi-animate/issues/67

Modified the flow of _setTimelinePosition:

1. If is crossthrough many frames, generate action frame on the way.
2. Do each action on the way, until `_goto` or `stop` is called.

### CODE REVIEW

**Comment by k8w** [comment]
I haven't resolve it if there is more than 1 loop.
It seems too complex...

For example:
Timeline: 0 1 2 3  (fps = 4, every frame have an action)

And for some reason, 3s past from last update.
So the actionFrames for `3->0` should be `0 1 2 3 0 1 2 3 0 1 2 3 0`.

**Comment by bigtimebuddy** [comment]
Thanks for this and your other PR. Could you undo the package.json changes where you changed the name of the package and urls?

**Comment by bigtimebuddy** [comment]
I have a bunch of catchup to do this week on PixiAnimate. There are a handful of lingering issues. Thanks for your patience.

**Comment by k8w** [comment]
Oops... didn't notice that...
I have submit a new one https://github.com/jiborobot/pixi-animate/pull/72

**Pull request closed without merging**
